version: '3.4'

services:
  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    container_name: Products.Api
    build:
      context: .
      dockerfile: Products.Api/Dockerfile

  products-db:
    # PostgreSQL section
    # image: postgres:latest
    # container_name: eshop-db
    # environment:
    #     POSTGRES_DB: eshop
    #     POSTGRES_USER: postgres
    #     POSTGRES_PASSWORD: "postgres"
    # volumes:
    #     - ./.containers/database:/var/lib/postgresql/data
    # ports:
    #     - "5432:5432"

    # MS SQL Server section
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Products.Db
    volumes:
        - ./.containers/database:/var/opt/mssql/data
    ports:
        - "1433:1433"
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Strong_password_123!"
